version: '3'

services:
  server:
    build: 
      context: server
    ports:
      - "8088:3001"
    environment: 
      PORT: 3001
      DB_HOST: db
    volumes:
      - ./server:/usr/src/app
    depends_on: 
      [db]
  
  db:
    image: mongo:4.2.5
    ports:
      - "27018:27017"
